---
- name: assert that variables are defined
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - autofs_mount
    - autofs_map

- name: install packages
  package: name=autofs

- name: configure /home
  template:
    src: templates/master.j2
    dest: /etc/auto.master
    owner: root
    group: root
    mode: 0644
  notify: "restart autofs"
  tags:
    - configuration

- name: ensure mountpoint exists
  file: 
    path: "{{ autofs_mount }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: autofs_mount is defined

- name: make sure autofs is running
  service: name=autofs state=started enabled=yes
