---
- name: make clean in build directory after install
  command: make clean
  args:
    chdir: "{{ slurm_build_dir }}"
  failed_when: false
  when: slurm_build_make_clean

- name: remove build directory
  file:
    path: "{{ slurm_build_dir }}"
    state: absent
  when: slurm_build_dir_cleanup
