---

- name: install munge
  package:
    name: munge
    state: present
  notify:
    - restart munge

- name: create munge.key
  template:
    src: templates/etc/munge/munge.key.j2
    dest: /etc/munge/munge.key
    mode: 0400
    owner: munge
  notify:
    - restart munge

- name: start munge
  service:
    name: munge
    enabled: yes
    state: started

- name: flush handlers to ensure munge gets restarted now
  meta: flush_handlers
