---
- name: install dependencies (Ubuntu)
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ pyxis_ubuntu_deps }}"
  when: ansible_distribution == "Ubuntu"

- name: install dependencies (EL)
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ pyxis_el_deps }}"
  when: ansible_os_family == "RedHat"

- name: install slurm-pmi hook
  file:
    path: /etc/enroot/hooks.d/50-slurm-pmi.sh
    state: link
    src: /usr/share/enroot/hooks.d/50-slurm-pmi.sh
  when: is_compute

- name: install slurm-pytorch hook
  file:
    path: /etc/enroot/hooks.d/50-slurm-pytorch.sh
    state: link
    src: /usr/share/enroot/hooks.d/50-slurm-pytorch.sh
  when: is_compute

- name: pyxis tasks
  include_tasks: pyxis.yml
  when: slurm_install_pyxis
  tags: pyxis

# Resize /run temporary file system, which is used to import docker image.
#  - Default pyxis runtime_path is: /run/pyxis
# If image is bigger than the file system, the importing will be failed
- name: resize /run partition
  mount:
    name: /run
    src: tmpfs
    opts: size={{ pyxis_run_tmpfs_size }}
    fstype: tmpfs
    state: mounted
  when: resize_run_partition
